export enum ENDPOINT {
  USER = '/user',
  AUTH = '/auth',
  CLASS = '/class',
  ATTENDANCE = '/attendance',
  SHEDULE = '/shedule',
  REPORT = '/report',
  TEACHER = '/teacherclass',
  STUDENTVIEW = '/studentview',
  STUDENT = '/student',
  NODEMAIL = '/newuser',
  SUBJECT = '/subject',
  HOLIDAY = '/holiday',
  LEAVE = '/leave',
}
